# generated by datamodel-codegen:
#   filename:  dbt_cloud-latest.json
#   timestamp: 2024-08-05T22:16:27+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class DbtCloud(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    project_id: str = Field(..., alias='project-id')
    defer_env_id: Optional[str] = Field(None, alias='defer-env-id')
